services:
  django:
    container_name: sagaart-django
    build:
      context: .
      dockerfile: .docker/django/Dockerfile
      args:
        DEPENDENCIES_DIR: /backend/sagaart_backend
        SCRIPT_DIR: /.docker/django
    restart: always
    ports:
      - "8000:8000"
    command: >
      sh -c "gunicorn --bind 0.0.0.0:8000 sagaart_backend.wsgi"
    depends_on:
      - postgres
    volumes:
      - ./backend/sagaart_backend:/usr/src/app/
      - sagaart_static_volume:/usr/src/app/static
      - sagaart_media_volume:/usr/src/app/media
    env_file:
      - ./.env

  node:
    container_name: sagaart-node
    build:
      context: ./frontend
      dockerfile: ../.docker/react/Dockerfile
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/public/:/usr/src/app/public/
      - ./frontend/src/:/usr/src/app/src/
      - sagaart_static_volume:/usr/src/app/static/
    command: cp -r /app/dist/. /static/
    depends_on:
      - django

  postgres:
    container_name: sagaart-postgres
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    ports:
      - "${PG_EXTERNAL_PORT:-54321}:5432"
    expose:
      - "${PG_EXTERNAL_PORT:-54321}"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - sagaart_postgres_volume:/var/lib/postgresql/data/
    env_file:
      - ./.env

  nginx:
    container_name: sagaart-nginx
    image: nginx:1.19.3
    ports:
      - "8899:80"
    depends_on:
      - django
    volumes:
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - sagaart_static_volume:/home/src/app/static
      - sagaart_media_volume:/home/src/app/media

volumes:
  sagaart_postgres_volume:
  sagaart_static_volume:
  sagaart_media_volume:
  
